// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYWHGkiW_yR8_8SWhczCz-QuhxiRYXXU',
    appId: '1:730491295964:web:b0114575f7060b891efc19',
    messagingSenderId: '730491295964',
    projectId: 'bharatmandiram-pocketfm-2956e',
    authDomain: 'bharatmandiram-pocketfm-2956e.firebaseapp.com',
    storageBucket: 'bharatmandiram-pocketfm-2956e.firebasestorage.app',
    measurementId: 'G-GT1B10CC22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEBJ1mKIu-bcGtaDta2WZ-ERu9yP-0jK8',
    appId: '1:730491295964:android:464ea3a6c186c1d91efc19',
    messagingSenderId: '730491295964',
    projectId: 'bharatmandiram-pocketfm-2956e',
    storageBucket: 'bharatmandiram-pocketfm-2956e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzuR4TvEBFEqmW5nOiridOuKQJGnqRG0',
    appId: '1:730491295964:ios:fd6878e5b7993db81efc19',
    messagingSenderId: '730491295964',
    projectId: 'bharatmandiram-pocketfm-2956e',
    storageBucket: 'bharatmandiram-pocketfm-2956e.firebasestorage.app',
    iosBundleId: 'com.bharatmandiram.pocketfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZzuR4TvEBFEqmW5nOiridOuKQJGnqRG0',
    appId: '1:730491295964:ios:fd6878e5b7993db81efc19',
    messagingSenderId: '730491295964',
    projectId: 'bharatmandiram-pocketfm-2956e',
    storageBucket: 'bharatmandiram-pocketfm-2956e.firebasestorage.app',
    iosBundleId: 'com.bharatmandiram.pocketfm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYYWHGkiW_yR8_8SWhczCz-QuhxiRYXXU',
    appId: '1:730491295964:web:6ce305b52b0e27841efc19',
    messagingSenderId: '730491295964',
    projectId: 'bharatmandiram-pocketfm-2956e',
    authDomain: 'bharatmandiram-pocketfm-2956e.firebaseapp.com',
    storageBucket: 'bharatmandiram-pocketfm-2956e.firebasestorage.app',
    measurementId: 'G-RMCE1XDZM7',
  );

}